<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SiteLink.API" Version="0.0.3" />
	</ItemGroup>
	
	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\..\SiteLink\SiteLink\bin\Release\net9.0\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\SiteLink\SiteLink\bin\Release\net9.0\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
